import { Button } from "@/components/ui/button";
import { ChevronDown, Zap, Code, Trophy } from "lucide-react";

const Hero = () => {
  const scrollToSection = (sectionId: string) => {
    const element = document.getElementById(sectionId);
    //logic generated by AI for smooth scrolling
    if (element) {
      const targetPosition = element.offsetTop;
      const startPosition = window.scrollY;
      const distance = targetPosition - startPosition;
      const duration = 1000; // Duration in milliseconds
      let startTime: number | null = null;

      const animateScroll = (currentTime: number) => {
        if (startTime === null) startTime = currentTime;
        const timeElapsed = currentTime - startTime;
        const run = easeInOutQuad(timeElapsed, startPosition, distance, duration);
        window.scrollTo(0, run);
        if (timeElapsed < duration) requestAnimationFrame(animateScroll);
      };

      const easeInOutQuad = (t: number, b: number, c: number, d: number) => {
        t /= d / 2;
        if (t < 1) return (c / 2) * t * t + b;
        t--;
        return (-c / 2) * (t * (t - 2) - 1) + b;
      };

      requestAnimationFrame(animateScroll);
    }
  };

  return (
    <section id="home" className="relative min-h-screen flex items-center justify-center bg-background">
      {/* Simple gradient background */}
      <div className="absolute inset-0 bg-gradient-to-br from-background to-primary/5"></div>

      {/* Content */}
      <div className="relative z-10 container mx-auto px-4 text-center">
        <div className="space-y-8">
          <img
            className="mx-auto w-48 h-auto" // Added width and height classes
            src="src/assets/botball-logo-light.svg" // Ensure this path is correct
            alt="TJ Botball Logo"
          />
          <h1 className="text-4xl md:text-6xl font-bold text-foreground">
            TJHSST Botball Robotics
          </h1>
          <p className="text-lg md:text-xl text-muted-foreground max-w-3xl mx-auto">
            The Official Botball Robotics team for Thomas Jefferson High School for Science and Technology
          </p>
          <p className="text-base md:text-lg text-muted-foreground max-w-2xl mx-auto">
            Designing, building, and programming two autonomous robots to compete at regional and international levels.
          </p>

          {/* CTA Buttons */}
          <div className="flex flex-col sm:flex-row gap-4 justify-center pt-8">
            <Button 
              size="lg"
              onClick={() => scrollToSection("about")}
            >
              Learn More
            </Button>
            <Button 
              variant="outline"
              size="lg"
              onClick={() => scrollToSection("team")}
            >
              Meet the Team
            </Button>
          </div>
        </div>

        {/* Scroll indicator */}
        <div 
          className="absolute -bottom-20 left-1/2 transform -translate-x-1/2 cursor-pointer" // Changed to -bottom-8
          onClick={() => scrollToSection("about")}
        >
          <ChevronDown className="h-6 w-6 text-muted-foreground animate-bounce" />
        </div>
      </div>
    </section>
  );
};

export default Hero;